### ISSUE TITLE
Repository Broken

### ISSUE THREAD

**Issue by McStyls** [Lugal-PCZ/bbapi_toolkit#1]
Hey, not sure if you know but your repository path is broken so the files are empty.  New to Git so I can't really help you sorry.

**Comment by Lugal-PCZ** [comment]
I just tested on two different systems, and can clone the project w/o any problem. Many of the files are just stubs, and I'm slowly building out functions in each category. Working functions currently exist in onapi/endpoints/constituents/user.py.

**Comment by McStyls** [comment]
ahhh gotya, ya I'm working on mine as well and I wanted to check a few things with yours.

I started out doing it in bash as I was just updating a few fields but once my scope started to grow I started in python.  I've just gotten to the point of put and post information.  I've also structured mine a little different preferring to create library files.

I look forward to seeing more of your work.




Kyle McMullin

IT Specialist

Shawnigan Lake School

________________________________
